### ISSUE TITLE
Deploy and Provision - HomeBox Docker Container

### ISSUE THREAD

**Issue by s0nt3k** [s0nt3k/wsldockersetup#2]
# Homebox Home Inventory & Management System
## Docker Container Deployment & Provisioning Guide

Homebox is the inventory and organization system built for the Home User! With a focus on simplicity and ease of use, Homebox is the perfect solution for your home inventory, organization, and management needs. While developing this project, I've tried to keep the following principles in mind:

## Step No. 1 - Login to the WSL Debian distro and create directories

- [ ] Open PowerShell and run the following cmdlet
Open PowerShell with the Windows Power User Menu [Win] + [X] when the menu displays release the keys and press [Alt] + [A]
```
wsl -d debian
cd\
```

- [ ] Create a directory to store the Homebox data files outside of the Docker container
```
sudo mkdir -p /homebox/data/
```
```
sudo chown 65532:65532 -R /homebox/data/
```

- [ ] Create a directory to store the Homebox docker compose yml file
```
sudo mkdir -p /docker/homebox
```
## Switch to the Homebox dir and download the docker compose file from github

- [ ] Use nano to create a docker-compose.yml file
```
nano /docker/homebox/docker-compose.yml
```

- [ ] Copy the following code and past it into the nano file editor

```
version: "3.4"

services:
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
#   image: ghcr.io/hay-kot/homebox:latest-rootless
    container_name: homebox
    restart: always
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - homebox-data:/homebox/data/
    ports:
      - 3100:7745

volumes:
   homebox-data:
     driver: local
```
